# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lihan/pio_qspi/qspi_pio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lihan/pio_qspi/qspi_pio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"piolib\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lihan/pio_qspi/qspi_pio/CMakeFiles /home/lihan/pio_qspi/qspi_pio//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lihan/pio_qspi/qspi_pio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qspi_test

# Build rule for target.
qspi_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qspi_test
.PHONY : qspi_test

# fast build rule for target.
qspi_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/build
.PHONY : qspi_test/fast

#=============================================================================
# Target rules for targets named pio

# Build rule for target.
pio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pio
.PHONY : pio

# fast build rule for target.
pio/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/CMakeFiles/pio.dir/build.make utils/piolib/CMakeFiles/pio.dir/build
.PHONY : pio/fast

#=============================================================================
# Target rules for targets named apitest

# Build rule for target.
apitest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apitest
.PHONY : apitest

# fast build rule for target.
apitest/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/apitest.dir/build.make utils/piolib/examples/CMakeFiles/apitest.dir/build
.PHONY : apitest/fast

#=============================================================================
# Target rules for targets named piotest

# Build rule for target.
piotest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piotest
.PHONY : piotest

# fast build rule for target.
piotest/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/piotest.dir/build.make utils/piolib/examples/CMakeFiles/piotest.dir/build
.PHONY : piotest/fast

#=============================================================================
# Target rules for targets named piopwm

# Build rule for target.
piopwm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piopwm
.PHONY : piopwm

# fast build rule for target.
piopwm/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/piopwm.dir/build.make utils/piolib/examples/CMakeFiles/piopwm.dir/build
.PHONY : piopwm/fast

#=============================================================================
# Target rules for targets named pioseq

# Build rule for target.
pioseq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pioseq
.PHONY : pioseq

# fast build rule for target.
pioseq/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/pioseq.dir/build.make utils/piolib/examples/CMakeFiles/pioseq.dir/build
.PHONY : pioseq/fast

#=============================================================================
# Target rules for targets named piows2812

# Build rule for target.
piows2812: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piows2812
.PHONY : piows2812

# fast build rule for target.
piows2812/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/piows2812.dir/build.make utils/piolib/examples/CMakeFiles/piows2812.dir/build
.PHONY : piows2812/fast

#=============================================================================
# Target rules for targets named dpi_csync

# Build rule for target.
dpi_csync: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dpi_csync
.PHONY : dpi_csync

# fast build rule for target.
dpi_csync/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/dpi_csync.dir/build.make utils/piolib/examples/CMakeFiles/dpi_csync.dir/build
.PHONY : dpi_csync/fast

#=============================================================================
# Target rules for targets named rp1sm

# Build rule for target.
rp1sm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rp1sm
.PHONY : rp1sm

# fast build rule for target.
rp1sm/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/rp1sm.dir/build.make utils/piolib/examples/CMakeFiles/rp1sm.dir/build
.PHONY : rp1sm/fast

#=============================================================================
# Target rules for targets named quadenc

# Build rule for target.
quadenc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quadenc
.PHONY : quadenc

# fast build rule for target.
quadenc/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/quadenc.dir/build.make utils/piolib/examples/CMakeFiles/quadenc.dir/build
.PHONY : quadenc/fast

#=============================================================================
# Target rules for targets named qspitest

# Build rule for target.
qspitest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qspitest
.PHONY : qspitest

# fast build rule for target.
qspitest/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/qspitest.dir/build.make utils/piolib/examples/CMakeFiles/qspitest.dir/build
.PHONY : qspitest/fast

#=============================================================================
# Target rules for targets named toggletest

# Build rule for target.
toggletest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 toggletest
.PHONY : toggletest

# fast build rule for target.
toggletest/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/toggletest.dir/build.make utils/piolib/examples/CMakeFiles/toggletest.dir/build
.PHONY : toggletest/fast

#=============================================================================
# Target rules for targets named ws2812test

# Build rule for target.
ws2812test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ws2812test
.PHONY : ws2812test

# fast build rule for target.
ws2812test/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/ws2812test.dir/build.make utils/piolib/examples/CMakeFiles/ws2812test.dir/build
.PHONY : ws2812test/fast

#=============================================================================
# Target rules for targets named clock10mhz

# Build rule for target.
clock10mhz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clock10mhz
.PHONY : clock10mhz

# fast build rule for target.
clock10mhz/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/clock10mhz.dir/build.make utils/piolib/examples/CMakeFiles/clock10mhz.dir/build
.PHONY : clock10mhz/fast

#=============================================================================
# Target rules for targets named clocksimple

# Build rule for target.
clocksimple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clocksimple
.PHONY : clocksimple

# fast build rule for target.
clocksimple/fast:
	$(MAKE) $(MAKESILENT) -f utils/piolib/examples/CMakeFiles/clocksimple.dir/build.make utils/piolib/examples/CMakeFiles/clocksimple.dir/build
.PHONY : clocksimple/fast

include/wizchip_qspi_pio.pio.o: include/wizchip_qspi_pio.pio.c.o
.PHONY : include/wizchip_qspi_pio.pio.o

# target to build an object file
include/wizchip_qspi_pio.pio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/include/wizchip_qspi_pio.pio.c.o
.PHONY : include/wizchip_qspi_pio.pio.c.o

include/wizchip_qspi_pio.pio.i: include/wizchip_qspi_pio.pio.c.i
.PHONY : include/wizchip_qspi_pio.pio.i

# target to preprocess a source file
include/wizchip_qspi_pio.pio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/include/wizchip_qspi_pio.pio.c.i
.PHONY : include/wizchip_qspi_pio.pio.c.i

include/wizchip_qspi_pio.pio.s: include/wizchip_qspi_pio.pio.c.s
.PHONY : include/wizchip_qspi_pio.pio.s

# target to generate assembly for a file
include/wizchip_qspi_pio.pio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/include/wizchip_qspi_pio.pio.c.s
.PHONY : include/wizchip_qspi_pio.pio.c.s

lib/ioLibrary_Driver/Application/loopback/loopback.o: lib/ioLibrary_Driver/Application/loopback/loopback.c.o
.PHONY : lib/ioLibrary_Driver/Application/loopback/loopback.o

# target to build an object file
lib/ioLibrary_Driver/Application/loopback/loopback.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Application/loopback/loopback.c.o
.PHONY : lib/ioLibrary_Driver/Application/loopback/loopback.c.o

lib/ioLibrary_Driver/Application/loopback/loopback.i: lib/ioLibrary_Driver/Application/loopback/loopback.c.i
.PHONY : lib/ioLibrary_Driver/Application/loopback/loopback.i

# target to preprocess a source file
lib/ioLibrary_Driver/Application/loopback/loopback.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Application/loopback/loopback.c.i
.PHONY : lib/ioLibrary_Driver/Application/loopback/loopback.c.i

lib/ioLibrary_Driver/Application/loopback/loopback.s: lib/ioLibrary_Driver/Application/loopback/loopback.c.s
.PHONY : lib/ioLibrary_Driver/Application/loopback/loopback.s

# target to generate assembly for a file
lib/ioLibrary_Driver/Application/loopback/loopback.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Application/loopback/loopback.c.s
.PHONY : lib/ioLibrary_Driver/Application/loopback/loopback.c.s

lib/ioLibrary_Driver/Ethernet/W6300/w6300.o: lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.o
.PHONY : lib/ioLibrary_Driver/Ethernet/W6300/w6300.o

# target to build an object file
lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.o
.PHONY : lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.o

lib/ioLibrary_Driver/Ethernet/W6300/w6300.i: lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.i
.PHONY : lib/ioLibrary_Driver/Ethernet/W6300/w6300.i

# target to preprocess a source file
lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.i
.PHONY : lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.i

lib/ioLibrary_Driver/Ethernet/W6300/w6300.s: lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.s
.PHONY : lib/ioLibrary_Driver/Ethernet/W6300/w6300.s

# target to generate assembly for a file
lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.s
.PHONY : lib/ioLibrary_Driver/Ethernet/W6300/w6300.c.s

lib/ioLibrary_Driver/Ethernet/socket.o: lib/ioLibrary_Driver/Ethernet/socket.c.o
.PHONY : lib/ioLibrary_Driver/Ethernet/socket.o

# target to build an object file
lib/ioLibrary_Driver/Ethernet/socket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/socket.c.o
.PHONY : lib/ioLibrary_Driver/Ethernet/socket.c.o

lib/ioLibrary_Driver/Ethernet/socket.i: lib/ioLibrary_Driver/Ethernet/socket.c.i
.PHONY : lib/ioLibrary_Driver/Ethernet/socket.i

# target to preprocess a source file
lib/ioLibrary_Driver/Ethernet/socket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/socket.c.i
.PHONY : lib/ioLibrary_Driver/Ethernet/socket.c.i

lib/ioLibrary_Driver/Ethernet/socket.s: lib/ioLibrary_Driver/Ethernet/socket.c.s
.PHONY : lib/ioLibrary_Driver/Ethernet/socket.s

# target to generate assembly for a file
lib/ioLibrary_Driver/Ethernet/socket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/socket.c.s
.PHONY : lib/ioLibrary_Driver/Ethernet/socket.c.s

lib/ioLibrary_Driver/Ethernet/wizchip_conf.o: lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.o
.PHONY : lib/ioLibrary_Driver/Ethernet/wizchip_conf.o

# target to build an object file
lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.o
.PHONY : lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.o

lib/ioLibrary_Driver/Ethernet/wizchip_conf.i: lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.i
.PHONY : lib/ioLibrary_Driver/Ethernet/wizchip_conf.i

# target to preprocess a source file
lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.i
.PHONY : lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.i

lib/ioLibrary_Driver/Ethernet/wizchip_conf.s: lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.s
.PHONY : lib/ioLibrary_Driver/Ethernet/wizchip_conf.s

# target to generate assembly for a file
lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.s
.PHONY : lib/ioLibrary_Driver/Ethernet/wizchip_conf.c.s

src/pio_func.o: src/pio_func.c.o
.PHONY : src/pio_func.o

# target to build an object file
src/pio_func.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/pio_func.c.o
.PHONY : src/pio_func.c.o

src/pio_func.i: src/pio_func.c.i
.PHONY : src/pio_func.i

# target to preprocess a source file
src/pio_func.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/pio_func.c.i
.PHONY : src/pio_func.c.i

src/pio_func.s: src/pio_func.c.s
.PHONY : src/pio_func.s

# target to generate assembly for a file
src/pio_func.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/pio_func.c.s
.PHONY : src/pio_func.c.s

src/qspi_test.o: src/qspi_test.c.o
.PHONY : src/qspi_test.o

# target to build an object file
src/qspi_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/qspi_test.c.o
.PHONY : src/qspi_test.c.o

src/qspi_test.i: src/qspi_test.c.i
.PHONY : src/qspi_test.i

# target to preprocess a source file
src/qspi_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/qspi_test.c.i
.PHONY : src/qspi_test.c.i

src/qspi_test.s: src/qspi_test.c.s
.PHONY : src/qspi_test.s

# target to generate assembly for a file
src/qspi_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/qspi_test.c.s
.PHONY : src/qspi_test.c.s

src/wizchip_spi.o: src/wizchip_spi.c.o
.PHONY : src/wizchip_spi.o

# target to build an object file
src/wizchip_spi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/wizchip_spi.c.o
.PHONY : src/wizchip_spi.c.o

src/wizchip_spi.i: src/wizchip_spi.c.i
.PHONY : src/wizchip_spi.i

# target to preprocess a source file
src/wizchip_spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/wizchip_spi.c.i
.PHONY : src/wizchip_spi.c.i

src/wizchip_spi.s: src/wizchip_spi.c.s
.PHONY : src/wizchip_spi.s

# target to generate assembly for a file
src/wizchip_spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qspi_test.dir/build.make CMakeFiles/qspi_test.dir/src/wizchip_spi.c.s
.PHONY : src/wizchip_spi.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... apitest"
	@echo "... clock10mhz"
	@echo "... clocksimple"
	@echo "... dpi_csync"
	@echo "... pio"
	@echo "... piopwm"
	@echo "... pioseq"
	@echo "... piotest"
	@echo "... piows2812"
	@echo "... qspi_test"
	@echo "... qspitest"
	@echo "... quadenc"
	@echo "... rp1sm"
	@echo "... toggletest"
	@echo "... ws2812test"
	@echo "... include/wizchip_qspi_pio.pio.o"
	@echo "... include/wizchip_qspi_pio.pio.i"
	@echo "... include/wizchip_qspi_pio.pio.s"
	@echo "... lib/ioLibrary_Driver/Application/loopback/loopback.o"
	@echo "... lib/ioLibrary_Driver/Application/loopback/loopback.i"
	@echo "... lib/ioLibrary_Driver/Application/loopback/loopback.s"
	@echo "... lib/ioLibrary_Driver/Ethernet/W6300/w6300.o"
	@echo "... lib/ioLibrary_Driver/Ethernet/W6300/w6300.i"
	@echo "... lib/ioLibrary_Driver/Ethernet/W6300/w6300.s"
	@echo "... lib/ioLibrary_Driver/Ethernet/socket.o"
	@echo "... lib/ioLibrary_Driver/Ethernet/socket.i"
	@echo "... lib/ioLibrary_Driver/Ethernet/socket.s"
	@echo "... lib/ioLibrary_Driver/Ethernet/wizchip_conf.o"
	@echo "... lib/ioLibrary_Driver/Ethernet/wizchip_conf.i"
	@echo "... lib/ioLibrary_Driver/Ethernet/wizchip_conf.s"
	@echo "... src/pio_func.o"
	@echo "... src/pio_func.i"
	@echo "... src/pio_func.s"
	@echo "... src/qspi_test.o"
	@echo "... src/qspi_test.i"
	@echo "... src/qspi_test.s"
	@echo "... src/wizchip_spi.o"
	@echo "... src/wizchip_spi.i"
	@echo "... src/wizchip_spi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

